BILLING_PROVIDER_STRIPE = "stripe"
BILLING_PROVIDER_PAYPAL = "paypal"

SUPPORTED_BILLING_PROVIDERS = frozenset(
    {
        BILLING_PROVIDER_STRIPE,
        BILLING_PROVIDER_PAYPAL,
    }
)

BILLING_CONNECT_STATUS_PENDING = "pending"
BILLING_CONNECT_STATUS_CONNECTED = "connected"
BILLING_CONNECT_STATUS_DISCONNECTED = "disconnected"

SUPPORTED_BILLING_CONNECT_STATUSES = frozenset(
    {
        BILLING_CONNECT_STATUS_PENDING,
        BILLING_CONNECT_STATUS_CONNECTED,
        BILLING_CONNECT_STATUS_DISCONNECTED,
    }
)

DEFAULT_BILLING_PROVIDER = BILLING_PROVIDER_STRIPE
DEFAULT_BILLING_CONNECT_STATUS = BILLING_CONNECT_STATUS_PENDING
